-- rby_mmo_maps: generated by tools/content-editor (do not hand-edit;
-- re-Save from the content editor, or maintain editor_project.lua).
return function(mod)

  mod.content.maps:patch("PALLET_TOWN", {
    blocks = {
      82,
      79,
      82,
      82,
      79,
      11,
      80,
      82,
      82,
      80,
      78,
      1,
      56,
      57,
      1,
      1,
      56,
      57,
      1,
      77,
      78,
      8,
      60,
      61,
      1,
      8,
      60,
      61,
      1,
      77,
      78,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      77,
      78,
      1,
      32,
      33,
      1,
      12,
      13,
      14,
      1,
      77,
      78,
      1,
      104,
      105,
      1,
      16,
      58,
      0,
      1,
      77,
      78,
      8,
      124,
      126,
      1,
      119,
      86,
      119,
      49,
      77,
      78,
      1,
      1,
      1,
      1,
      116,
      116,
      10,
      49,
      77,
      80,
      10,
      29,
      30,
      97,
      97,
      97,
      97,
      97,
      79,
    },
    borderBlock = 11,
    connections = {
      north = {
        map = "ROUTE_1",
        offset = 0,
      },
      south = {
        map = "ROUTE_21",
        offset = 0,
      },
    },
    height = 9,
    id = "PALLET_TOWN",
    index = 0,
    label = "PalletTown",
    objects = {
      {
              hidden = true,
              index = 1,
              movement = "STAY",
              name = "PALLETTOWN_OAK",
              range = "NONE",
              sprite = "SPRITE_OAK",
              text = "TEXT_PALLETTOWN_OAK",
              x = 8,
              y = 5,
            },
      {
              index = 2,
              movement = "WALK",
              name = "PALLETTOWN_GIRL",
              range = "ANY_DIR",
              sprite = "SPRITE_GIRL",
              text = "TEXT_PALLETTOWN_GIRL",
              x = 3,
              y = 8,
            },
      {
              index = 3,
              movement = "WALK",
              name = "PALLETTOWN_FISHER",
              range = "ANY_DIR",
              sprite = "SPRITE_FISHER",
              text = "TEXT_PALLETTOWN_FISHER",
              x = 11,
              y = 14,
            },
      {
              index = 4,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_GUARD",
              text = "TEXT_PALLET_TOWN_OBJ4",
              x = 5,
              y = 14,
            },
    },
    signs = {
      {
              text = "TEXT_PALLETTOWN_OAKSLAB_SIGN",
              x = 13,
              y = 13,
            },
      {
              text = "TEXT_PALLETTOWN_PLAYERSHOUSE_SIGN",
              x = 3,
              y = 5,
            },
      {
              text = "TEXT_PALLETTOWN_RIVALSHOUSE_SIGN",
              x = 11,
              y = 5,
            },
      {
              text = "TEXT_PALLET_TOWN_SIGN4",
              x = 3,
              y = 13,
            },
      {
              text = "TEXT_PALLET_TOWN_SIGN5",
              x = 5,
              y = 13,
            },
    },
    tileset = "OVERWORLD",
    warps = {
      {
              destMap = "REDS_HOUSE_1F",
              destWarp = 1,
              x = 5,
              y = 5,
            },
      {
              destMap = "BLUES_HOUSE",
              destWarp = 1,
              x = 13,
              y = 5,
            },
      {
              destMap = "OAKS_LAB",
              destWarp = 2,
              x = 12,
              y = 11,
            },
    },
    width = 10,
  })

  mod.content.field:patch("superRod", {
    PALLET_TOWN = {
      {
              level = 15,
              species = "TENTACOOL",
            },
      {
              level = 15,
              species = "POLIWAG",
            },
    },
  })

  mod.content.text:override("_PALLET_TOWN_NPC1", "PALLET TOWN HOTEL is under construction.")
  mod.content.text:override("_PALLET_TOWN_SIGN4", "PALLET TOWN HOTEL")
  mod.content.text:override("_PALLET_TOWN_SIGN5", "PALLET TOWN HOTEL is under constrution.")

  mod.content.text_pointers:patch("PalletTown", {
    TEXT_PALLET_TOWN_NPC1 = {
      text = "_PALLET_TOWN_NPC1",
    },
    TEXT_PALLET_TOWN_SIGN4 = {
      text = "_PALLET_TOWN_SIGN4",
    },
    TEXT_PALLET_TOWN_SIGN5 = {
      text = "_PALLET_TOWN_SIGN5",
    },
  })

  mod.content.map_scripts:register("PALLET_TOWN", {
    talk = {
      TEXT_PALLET_TOWN_NPC1 = {
        {
                  "show_text",
                  "TEXT_PALLET_TOWN_NPC1",
                },
        {
                  "label",
                  "end",
                },
      },
    },
  })

  -- Outside maps: block stock every-tile indoor wilds (index >= 37)
  do
    local outsideMaps = {
      ["PALLET_TOWN"] = true,
    }
    mod.hooks:wrap("encounter.roll", function(next, encDef, ctx)
      if ctx and ctx.terrain == "indoor" and ctx.mapId
         and outsideMaps[ctx.mapId] then
        return nil
      end
      return next(encDef, ctx)
    end)
  end

end
